server:
  host: "127.0.0.1"
  port: 7047

tls-signature:
  private-key-pem-path: "./src/fixtures/notary.key"
  certificate-pem-path: "./src/fixtures/notary.crt"

notary-signature:
  private-key-pem-path: "./src/fixtures/notaryEC.key"

logging:
  default-level: DEBUG
